# Generated by Django 3.1 on 2020-08-04 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_date',
        ),
        migrations.AddField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time ended'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_length',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='result_text',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='time started'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
