# Generated by Django 3.1 on 2020-08-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
